# Generated by Django 3.0.6 on 2020-08-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titel',
            new_name='title',
        ),
    ]
